services:
  php:
    build: .
    ports:
      - "8085:80"
    depends_on:
      - db
    volumes:
      - ./src:/var/www/html

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: db_belajar
      MYSQL_USER: userku
      MYSQL_PASSWORD: passku
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      # Opsi: set upload limit jika mau import SQL besar
      UPLOAD_LIMIT: 256M
    ports:
      - "8081:80"

volumes:
  dbdata:
    driver: local



